- name: Verify variables are set
  assert:
    that: "{{ item }} is defined"
  with_items:
    - mr_provisioner_machine_name

- name: Get IP of provisioned machine
  mr_provisioner_get_ip:
    mrp_url: "{{ mr_provisioner_url }}"
    mrp_token: "{{ mr_provisioner_auth_token }}"
    machine_name: "{{ mr_provisioner_machine_name }}"
    interface_name: "{{ mr_provisioner_interface_name|default('eth1') }}"
  register: get_ip
- debug: var=get_ip

- name: Add provisioned machine as host
  add_host:
          name: "{{ get_ip['ip'] }}"
          groups: mr_provisioner_hosts
  when: get_ip['ip'] is defined
